version: "3.9"
services:
  database:
    image: postgres:alpine
    restart: 'always'
    environment:
      - POSTGRES_USER=ghh-web
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=ghh-api
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - DB_EXTENSION=uuid-ossp
    ports:
      - "5433:5432"
    networks:
      - backend
    volumes:
      - data:/var/lib/postgresql/data
      - ./pg-extensions.sql:/docker-entrypoint-initdb.d/uuid-ossp.sql
  server:
    restart: 'always'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=local
      - PERMISSION_TOKEN=localadmin
      - PERMISSION_HOST=authzed:50051
      - DB_USER=ghh-web
      - DB_HOST=database
      - DB_PASS=mysecretpassword
      - DB_NAME=ghh-api
      - DB_PORT=5433
      - DB_TIMEZONE=America/Santiago
      - PORT=4000
      - APP_URL=http://localhost:3000/
      - SIGN_KEY=8kzz3S4mVmx3BodlQiba
      - CONTACT_EMAIL=nicolas.dev.py@gmail.com
      - SENDGRID_KEY=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
      - WS_USER=AutentiaManager
      - WS_PASS=4gj=U4A%F5
      - WS_OPER=0000005555-7
      - WS_URL=http://cap.autentia.cl/
      - WS_USER_LATAM=AutentiaManager
      - WS_PASS_LATAM=4gj=U4A%F5
      - WS_OPER_LATAM=0000005555-7
      - WS_URL_LATAM=http://stg.autentia.io/
    depends_on:
      - database
    networks:
      - backend
    ports:
      - "4000:4000"
volumes:
  data:
networks:
  backend:
